### PR TITLE
Add Camera and VideoCamera examples.

### LINKED ISSUE #19: Add examples for Camera and VideoCamera
Please add examples for the new capabilities [Camera](https://iot.mozilla.org/schemas/#Camera) and [VideoCamera](https://iot.mozilla.org/schemas/#VideoCamera).

### PR DESCRIPTION
**Pull request by mrstegeman**
Fixes #19

### CODE REVIEW

**Comment by mrstegeman** [comment]
This includes the changes from #20, so we should merge that first. Also, you'll need to have git-lfs installed to pull down the image and video.

**Comment by hobinjk** [comment]
The camera's image doesn't appear to be working but the loop of the video is great!

**Comment by mrstegeman** [comment]
Did you run `npm install` to pull in the new dependency?

**Comment by hobinjk** [comment]
Yes, I'm getting `The image "blob:https://hobinjk-laptop-test.mozilla-iot.org/fb10da67-f556-e14f-bf0a-89be351e9c62" cannot be displayed because it contains errors` and no errors in the gateway's log

**Comment by mrstegeman** [comment]
Try a hard refresh in the browser. Also, do you have the following file? `~/.mozilla-iot/media/virtual-things/image.png`

**Comment by hobinjk** [comment]
I figured it out, it's because I wanted to see what would happen if I didn't initially run git-lfs so the image.png in the media directory you mentioned is the git-lfs placeholder instead of the real image.png that showed up after I ran git-lfs.

I'm not sure why restarting the gateway/adapter wouldn't copy over the new file but this LGTM now

**Comment by mrstegeman** [comment]
The adapter only copies the image file if it doesn't already exist, which is why the placeholder remained.

Are you good with #20 as well?

**Comment by hobinjk** [comment]
Yep, left a :+1: on that for completeness

**Pull request merged**
